export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorForBlueBackground: "#D8ECFE",
  colorForNGreenIcon: "#88AA4D",
  colorForAssortmentBackground: "#F7F7F7",
  colorForRedIcon: "#F75531",
  colorFarmCard: "#E1EDCE",
  colorShopCard: "#F8DDD7",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  panelBackgroundColor: "#88aa4d",
  panelBackgroundColorDanger: "#f75531",
  backgroundColorGray: "#f7f7f7",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  headerHeight: "80px",
  pageWidth: "1280px"
};
